version: "3.8"

services:

  frontend:
    container_name: frontend
    build:
      context: ./frontend
      #target: 'develop-stage'
    ports:
      - "8000:80"
    volumes:
      - './frontend:/app'
    #command: /bin/sh -c "yarn && quasar dev"
    networks:
      - internal

  api:
    container_name: api
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 8080
    depends_on:
      - zookeeper
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=8080"
    networks:
      - internal
  
  channel:
    container_name: channel
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: channel
    depends_on:
      - zookeeper
    networks:
      - internal
  
  user:
    container_name: user
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: user
    depends_on:
      - zookeeper
    networks:
      - internal
  
  project:
    container_name: project
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: project
    depends_on:
      - zookeeper
    networks:
      - internal
  
  node:
    container_name: node
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: node
    depends_on:
      - zookeeper
    networks:
      - internal
  
  exams:
    container_name: exams
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: exams
    depends_on:
      - zookeeper
    networks:
      - internal
  
  hub:
    container_name: hub
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: hub
    depends_on:
      - zookeeper
    networks:
      - internal

  vidaas:
    container_name: vidaas
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: vidaas
    depends_on:
      - zookeeper
    networks:
      - internal

  file:
    container_name: file
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: file
    depends_on:
      - zookeeper
    networks:
      - internal
    volumes:
      - exams_data:/usr/share/exams

  docsign:
    container_name: docsign
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: docsign
    depends_on:
      - zookeeper
    networks:
      - internal
    volumes:
      - ./templates:/usr/share/exams/templates

  docsign-slave1:
    container_name: docsign-slave1
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: docsign
    depends_on:
      - zookeeper
    networks:
      - internal
    volumes:
      - ./templates:/usr/share/exams/templates

  docsign-slave2:
    container_name: docsign-slave2
    restart: unless-stopped
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: docsign
    depends_on:
      - zookeeper
    networks:
      - internal
    volumes:
      - ./templates:/usr/share/exams/templates
      - /usr/share/exams

  zookeeper:
    container_name: zookeeper
    restart: unless-stopped
    hostname: zookeeper
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    #volumes:
    #  - ./vols/vol1/zk-data:/var/lib/zookeeper/data
    #  - ./vols/vol2/zk-txn-logs:/var/lib/zookeeper/log

    networks:
      - internal

  kafka1:
    hostname: kafka1
    container_name: kafka1
    restart: unless-stopped
    image: 'confluentinc/cp-kafka:latest'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka1
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka1:19092,OUTSIDE://kafka1:9092 
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:19092, OUTSIDE://:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_PROTOCOL_LISTENERS: INTERNAL://:19092, OUTSIDE://:9092
      KAFKA_INTER_BROKER_PROTOCOL_ADVERTISED_LISTENERS: INTERNAL://:19092, OUTSIDE://:9092
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
      
    depends_on:
      - zookeeper
    #volumes:
    #  - ./vols/vol3/kafka1-data:/var/lib/kafka/data

    networks:
      - internal

  kafka2:
    hostname: kafka2
    container_name: kafka2
    restart: unless-stopped
    image: 'confluentinc/cp-kafka:latest'
    environment:
      KAFKA_BROKER_ID: 2
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka2
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka2:19093,OUTSIDE://kafka2:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:19093, OUTSIDE://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_PROTOCOL_LISTENERS: INTERNAL://:19093, OUTSIDE://:9093
      KAFKA_INTER_BROKER_PROTOCOL_ADVERTISED_LISTENERS: INTERNAL://:19093, OUTSIDE://:9093
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
      
    depends_on:
      - zookeeper
    #volumes:
    #  - ./vols/vol3/kafka2-data:/var/lib/kafka/data

    networks:
      - internal

  kafka3:
    hostname: kafka3
    container_name: kafka3
    restart: unless-stopped
    image: 'confluentinc/cp-kafka:latest'
    environment:
      KAFKA_BROKER_ID: 3
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka3
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka3:19094,OUTSIDE://kafka2:9094
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:19094, OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_PROTOCOL_LISTENERS: INTERNAL://:19094, OUTSIDE://:9094
      KAFKA_INTER_BROKER_PROTOCOL_ADVERTISED_LISTENERS: INTERNAL://:19094, OUTSIDE://:9094
      KAFKA_DEFAULT_REPLICATION_FACTOR: 3
      KAFKA_NUM_PARTITIONS: 3
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
      
    depends_on:
      - zookeeper
    #volumes:
    #  - ./vols/vol3/kafka3-data:/var/lib/kafka/data

    networks:
      - internal

  control-center:
      container_name: control-center
      restart: unless-stopped
      image: confluentinc/cp-enterprise-control-center:latest
      platform: linux/arm64
      hostname: control-center
      depends_on:
        - kafka1
      ports:
        - 9021:9021
      expose:
        - 9021

      environment:
        CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka1:19092,kafka2:19093,kafka3:19094
        CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        CONTROL_CENTER_REPLICATION_FACTOR: 3
        CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 3
        CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 3
        CONFLUENT_METRICS_TOPIC_REPLICATION: 3
        CONTROL_CENTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"

        PORT: 9021
      networks:
        - internal

  traefik:
    hostname: traefik
    restart: unless-stopped
    container_name: traefik
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "traefik.frontend.rule=Host:frontend"
    ports:
      - "80:80"
      - "8080:8080"

    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
  
  prometheus:
    hostname: prometheus
    container_name: prometheus
    restart: unless-stopped
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
    networks:
      - internal

  grafana:
    hostname: grafana
    container_name: grafana
    restart: unless-stopped
    image: grafana/grafana
    ports:
      - 3000:3000
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
    networks:
      - internal

  redis:
    hostname: redis
    container_name: redis
    restart: unless-stopped
    image: redis:latest
    ports:
      - '6379:6379'
    environment:
      ##- REDIS_REPLICATION_MODE: "master"
      - ALLOW_EMPTY_PASWORD= yes
    volumes:
      - ./vols/vol4/redis_data:/var/lib/redis-persistence/data
    networks:
      - internal
    command: redis-server --requirepass setecodemiguelsete7sete --maxmemory 100mb

networks:
  internal:

volumes:
  redis_data:
  exams_data:
    external: true
