version: "3.3"

services:

  api:
    container_name: api
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: api
      PORT: 8080
    depends_on:
      - zookeeper
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api-gw.rule=PathPrefix(`/`)"
      - "traefik.http.services.api-gw.loadbalancer.server.port=8080"
    networks:
      - internal
  user-producer:
    container_name: user-producer
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: user-producer
    depends_on:
      - zookeeper
    networks:
      - internal

  user:
    container_name: user
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: user
    depends_on:
      - zookeeper
    networks:
      - internal
  
  project:
    container_name: project
    build:
      context: .
    image: moleculer-project
    env_file: docker-compose.env
    environment:
      SERVICES: project
    depends_on:
      - zookeeper
    networks:
      - internal

  zookeeper:
    container_name: zookeeper
    hostname: zookeeper
    image: 'confluentinc/cp-zookeeper:latest'
    environment:
      - ALLOW_ANONYMOUS_LOGIN=yes
      - ZOOKEEPER_CLIENT_PORT=2181
    
    networks:
      - internal

  kafka:
    hostname: kafka
    container_name: kafka
    image: 'confluentinc/cp-kafka:latest'
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_HOST_NAME: kafka
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,OUTSIDE://kafka:9094 
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_LISTENERS: INTERNAL://:9092, OUTSIDE://:9094
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT, OUTSIDE:PLAINTEXT
      KAFKA_INTER_BROKER_PROTOCOL_LISTENERS: INTERNAL://:9092, OUTSIDE://:9094
      KAFKA_INTER_BROKER_PROTOCOL_ADVERTISED_LISTENERS: INTERNAL://:9092, OUTSIDE://:9094
      KAFKA_HEAP_OPTS: "-Xmx512M -Xms256M"
      
    depends_on:
      - zookeeper
    volumes:
      - ./kafka_data:/kafka_data

    networks:
      - internal

  control-center:
      container_name: control-center
      image: confluentinc/cp-enterprise-control-center:latest
      platform: linux/arm64
      hostname: control-center
      depends_on:
        - kafka
      ports:
        - 9021:9021
      expose:
        - 9021

      environment:
        CONTROL_CENTER_BOOTSTRAP_SERVERS: 'kafka:9092'
        CONTROL_CENTER_ZOOKEEPER_CONNECT: 'zookeeper:2181'
        CONTROL_CENTER_REPLICATION_FACTOR: 1
        CONTROL_CENTER_INTERNAL_TOPICS_PARTITIONS: 1
        CONTROL_CENTER_MONITORING_INTERCEPTOR_TOPIC_PARTITIONS: 1
        CONFLUENT_METRICS_TOPIC_REPLICATION: 1
        PORT: 9021
      networks:
        - internal

  kafka-topics-generator:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - kafka
    entrypoint: [ '/bin/sh', '-c' ]
    command: |
      "
      # blocks until kafka is reachable
      kafka-topics --bootstrap-server kafka:9092 --list

      echo -e 'Creating kafka topics'
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic user --replication-factor 1 --partitions 2
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic hub --replication-factor 1 --partitions 2
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic node --replication-factor 1 --partitions 2
      kafka-topics --bootstrap-server kafka:9092 --create --if-not-exists --topic project --replication-factor 1 --partitions 2

      echo -e 'Successfully created the following topics:'
      kafka-topics --bootstrap-server kafka:9092 --list
      "
    networks:
      - internal

  traefik:
    hostname: traefik
    container_name: traefik
    image: traefik:v2.1
    command:
      - "--api.insecure=true" # Don't do that in production!
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
    ports:
      - "80:80"
      - "8080:8080"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
    networks:
      - internal
      - default
  
  prometheus:
    hostname: prometheus
    container_name: prometheus
    image: prom/prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus:/etc/prometheus
    networks:
      - internal

  grafana:
    hostname: grafana
    container_name: grafana
    image: grafana/grafana
    ports:
      - "3000:3000"
    volumes:
      - ./config/grafana:/etc/grafana/provisioning
    networks:
      - internal

networks:
  internal:

volumes:
  data:
