{
 "title": "Moleculer overview",
 "tags": [ "moleculer overview" ],
 "time": { "from": "now-1h", "to": "now" },
 "templating": {
  "list": [
   { "name": "namespace", "query": "process_uptime" }
  ]
 },
 "panels": [
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (namespace) (moleculer_registry_nodes_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 2, "x": 2, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum by (namespace) (moleculer_registry_services_total{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "RPS",
   "type": "singlestat",
   "gridPos": { "h": 2, "w": 5, "x": 4, "y": 0 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "avg(moleculer_request_total_rate{namespace=\"$namespace\"})"
    }
   ]
  },
  {
   "title": "Active requests",
   "type": "stat",
   "gridPos": { "h": 2, "w": 15, "x": 9, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_request_active{namespace=\"$namespace\"})",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Running services",
   "type": "bargauge",
   "gridPos": { "h": 13, "w": 9, "x": 0, "y": 2 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(moleculer_registry_service_endpoints_total{namespace=\"$namespace\"}) by (service)",
     "legendFormat": "{{service}}"
    }
   ]
  },
  {
   "title": "Memory Used",
   "type": "graph",
   "gridPos": { "h": 6, "w": 15, "x": 9, "y": 2 },
   "yaxes": [
    { "format": "decbytes" }
   ],
   "targets": [
    {
     "expr": "process_memory_heap_size_used{namespace=\"$namespace\"}",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Action calls",
   "type": "graph",
   "gridPos": { "h": 7, "w": 15, "x": 9, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(moleculer_request_total_rate{namespace=\"$namespace\"}) by (service)",
     "legendFormat": "{{service}}"
    },
    {
     "expr": "sum(moleculer_request_error_total_rate{namespace=\"$namespace\"}) by (service)",
     "legendFormat": "{{service}} errors"
    }
   ]
  },
  {
   "title": "Requests",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 15 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(moleculer_request_total_rate{namespace=\"$namespace\"}) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Response time",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 20 },
   "yaxes": [
    { "format": "dtdurationms" }
   ],
   "targets": [
    {
     "expr": "max(moleculer_request_time_max{namespace=\"$namespace\"}) by (action)",
     "legendFormat": "{{action}}"
    }
   ]
  },
  {
   "title": "Error type",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 25 },
   "yaxes": [
    { "format": "short", "label": "error rate" }
   ],
   "targets": [
    {
     "expr": "max(moleculer_request_error_total_rate{namespace=\"$namespace\"}) by (errorName)",
     "legendFormat": "{{errorName}}"
    }
   ]
  }
 ]
}