let user = {
  name: string,
  surname: string,
  email: string | null,
  phone: string | null,
  access_level: int,
  cpf: string | null,
  scope: [string] | null,
  password: string,
  doc_type: string,
  doc_id: string,
  doc_uf: string,
  avatar: string,
  bias: string,
  fbuid: string,
  active: boolean,
  projects: [int],
  nodes: [int],
  hubs: [int],
};
